[package]
name = "zk-for-supply-chain-in-sp1-program"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
sp1-zkvm = "4.0.0"
#sp1-zkvm = { path = "../../../crates/zkvm/entrypoint" }
#chess = "3.2.0"
serde = { version = "1.0", features = ["derive"] }